services:
  db:
    image: postgres:15
    container_name: freelancia_db_2
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-freelancia}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "7001:5432"

volumes:
  db_data:
